# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2545b299795fa48c333d22f5776dcc4f5c9fc757f61f6f9b81554b7bf3e07721590e11414716b3372d220a6a2ebcc6943cd67506b4e970df866c44ed43622be7

test:
  secret_key_base: 2639cc60b145b8fa72486464472b056f42b5733d3e4f9b01a9a32fe6ee34d91156d5599214a970c74fb0a945401883b5f84b2481ea2cd325235d450eca17096f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
